### ISSUE TITLE
[BUG] calculation of TREND fails

### ISSUE THREAD

**Issue by emoe71** [MadMonkey87/Homey.InsightTrends#3]
**Describe the bug**

When TREND is calculated in flow the value is very low, while in "app config" it calculates rigthly. Other values like AVERAGE and MAX calculates right.

**Expected behavior**
Same value in calculated flow and "app conig"

**Screenshots**

![Screenshot_20210413-202541_Homey](https://user-images.githubusercontent.com/81044842/114602081-7fe9fa80-9c96-11eb-8127-07754e624d0b.jpg)

![Screenshot_20210413-202229_Homey](https://user-images.githubusercontent.com/81044842/114601662-0eaa4780-9c96-11eb-9a1d-9252d5992f7c.jpg)

![Screenshot_20210413-203133_Homey](https://user-images.githubusercontent.com/81044842/114602783-49f94600-9c97-11eb-89c9-c17f252fff2b.jpg)

![Screenshot_20210413-203325_Homey](https://user-images.githubusercontent.com/81044842/114603001-82991f80-9c97-11eb-96ba-1dfdab6210da.jpg)

**Additional context**
 Tried different sensors, same error.

**Comment by MadMonkey87** [comment]
Thx for this finding! Please check out if the next beta resolves this: https://homey.app/de-ch/app/ch.philippewechsler.trends/Insight-Trends/test/

**Comment by emoe71** [comment]
👍 tanks, now its working. I will try to use it for "outdoor temperatur compensated" heat adjustment.
