### ISSUE TITLE
[BUG] Number of datapoint not correct

### ISSUE THREAD

**Issue by BOverdevest** [MadMonkey87/Homey.InsightTrends#5]
**Describe the bug**
The number of data points reported in a flow stays fixed (for me it stays at 167 for a 7 day period)

**To Reproduce**
Steps to reproduce the behaviour:
1. Data set is Weight as measured by a Whithings weighing scale.
2. every time a new measurement is reported the data set is processed 
3. In the next flow, when completed, the data is reported in a notification (latest weight, trend, average weigh over 7 days and no. of data points )
4. as i measure daily no of data points in a week should be 5-10. it is reported to be 167
5. For the last week this number has not changed
6. same behaviour is seen in Insight Trends.
7. Testing for different no of days
 7 days = 167 points
10 days = 239 points
3 days = 71 points
 1 day  287 points
24 hours = 287 points
12 hours = 143 points
1 hour = 718 points

it seems for >1 days, it shows no of hours
for 1 day and below, 10 minute interval
for 1 hour and below, 5 sec interval

**Expected behavior**
for the number of data points report to be inline with the actual number of data points in the data

**Additional context**

**Comment by MadMonkey87** [comment]
Hi, this is actually not a bug but homey's behaviour. The internals are not documented but you can see the exact same behaviour also in the official insights view. If you select a short scope (1 hour for example) you see the values as they were reported by the hardware. When you then select a a larger scope it seems that homey does not have all data available and only get's you back an approximation. I guess this could be to save storage but also cpu cycles. Please ask Athom for more details.

Here are some screenshots of the insights. A one hour scope shows "more details" as it has a lot of data points: 
![image](https://user-images.githubusercontent.com/29612400/114823359-b709fa00-9dc3-11eb-9a44-195e309cf561.png)

24h scope on the other side is less detailed and has less details:
![image](https://user-images.githubusercontent.com/29612400/114823460-dd2f9a00-9dc3-11eb-9c11-e089c9c52b00.png)

**Comment by BOverdevest** [comment]
Thanks for looking into this.
Understanding a bit better, using your (incredible) tool for equal periodic, high frequency measurements would mathematically be ok.
But if you have not evenly spaced measurements the result goes off. As a simplified example, if i weigh myself on Monday, and then Thursday and Friday, the Monday value will stand for Tuesday and Wednesday as well.  It will count 3 times as heavy in the trend and average being calculated. (a simplified depiction).

Good to understand, but not a lot we (you) can do about it, if this is how data is handled in Homey.
I just have to make sure i hit the scales everyday
